const cts = {
	VALID_HEAD_COMMAND_REGEXP: /(::mod|takeover|begin|help|view|plant|water|harvest|daily|buy|sell|auction)/i,
	cropTypes: {
		_seed_types_regexp: /^(wheat|strawberry|poppy|blueberry|purpleTulip|sunflower|goldenSunflower|pinkTulip|goldenWheat|lilyValley)$/i,
		wheat: {
			watersRequired: 3,
			earnings: 35,
		},
		strawberry: {
			watersRequired: 4,
			earnings: 40,
		},
		poppy: {
			watersRequired: 3,
			earnings: 60,
		},
		blueberry: {
			watersRequired: 4,
			earnings: 90,
		},
		purpleTulip: {
			watersRequired: 4,
			earnings: 65,
		},
		sunflower: {
			watersRequired: 5,
			earnings: 90,
		},
		goldenSunflower: {
			watersRequired: 6,
			earnings: 120,
		},
		pinkTulip: {
			watersRequired: 6,
			earnings: 100,
		},
		goldenWheat: {
			watersRequired: 8,
			earnings: 150,
		},
		lilyValley: {
			watersRequired: 12,
			earnings: 90,
		},
	},
	NEW_USER_JSON: {
		farm: [
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
		],
		lastWater: 0,
		coins: 0,
		lastDaily: 0,
		seedsInventory: {
			wheatSeeds: 5,
			strawberrySeeds: 0,
			poppySeeds: 0,
			blueberrySeeds: 0,
			purpleTulipSeeds: 0,
			sunflowerSeeds: 0,
			goldenSunflowerSeeds: 0,
			pinkTulipSeeds: 0,
			goldenWheatSeeds: 0,
			lilyValleySeeds: 0,
		},
		cropsInventory: {
			wheatCrops: 0,
			strawberryCrops: 0,
			poppyCrops: 0,
			blueberryCrops: 0,
			purpleTulipCrops: 0,
			sunflowerCrops: 0,
			goldenSunflowerCrops: 0,
			pinkTulipCrops: 0,
			goldenWheatCrops: 0,
			lilyValleyCrops: 0,
		},
		username: 'ZZZ-DU',
	},
	newFarmDefault: `{"growthLevel":0,"plantedAt":null,"seedType":null,"secret":false,"lastWater":0,"fertilizerCount":0}`,
	test: [['help'], ['view', 'farm'], ['view', 'inventory'], ['view', 'coins'], ['plant', 'wheat', 'spot', '1'], ['water'], ['harvest', 'spot', '1'], ['daily'], ['buy']],
	auctionHelp: `insert auction docs`,
};

module.exports.cts = function () {
	return cts;
};
