module.exports = {
	VALID_HEAD_COMMAND_REGEXP: /(::mod|::beta|takeover|begin|help|view|plant|water|harvest|daily|buy|sell|bid)/i,
	cropTypes: {
		_seed_types_regexp: /^(wheat|strawberry|poppy|blueberry|purpleTulip|sunflower|goldenSunflower|pinkTulip|goldenWheat|lilyValley)$/i,
		wheat: {
			watersRequired: 3,
			earnings: 35,
		},
		strawberry: {
			watersRequired: 4,
			earnings: 40,
		},
		poppy: {
			watersRequired: 3,
			earnings: 60,
		},
		blueberry: {
			watersRequired: 4,
			earnings: 90,
		},
		purpletulip: {
			watersRequired: 4,
			earnings: 65,
		},
		sunflower: {
			watersRequired: 5,
			earnings: 90,
		},
		goldensunflower: {
			watersRequired: 6,
			earnings: 120,
		},
		pinktulip: {
			watersRequired: 6,
			earnings: 100,
		},
		goldenwheat: {
			watersRequired: 8,
			earnings: 150,
		},
		lilyvalley: {
			watersRequired: 12,
			earnings: 90,
		},
	},
	NEW_USER_JSON: {
		farm: [
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
			{
				fertilizerCount: 0,
				growthLevel: 0,
				lastWater: 0,
				plantedAt: null,
				secret: false,
				seedType: null,
			},
		],
		lastWater: 0,
		coins: 0,
		lastDaily: 0,
		seedsInventory: {
			wheatseeds: 5,
			strawberryseeds: 0,
			poppyseeds: 0,
			blueberryseeds: 0,
			purpletulipseeds: 0,
			sunflowerseeds: 0,
			goldensunflowerseeds: 0,
			pinktulipseeds: 0,
			goldenwheatseeds: 0,
			lilyvalleyseeds: 0,
		},
		cropsInventory: {
			wheatcrops: 0,
			strawberrycrops: 0,
			poppycrops: 0,
			blueberrycrops: 0,
			purpletulipcrops: 0,
			sunflowercrops: 0,
			goldensunflowercrops: 0,
			pinktulipcrops: 0,
			goldenwheatcrops: 0,
			lilyvalleycrops: 0,
		},
		level: 0,
		username: 'ZZZ-DU',
	},
	newFarmDefault: `{"growthLevel":0,"plantedAt":null,"seedType":null,"secret":false,"lastWater":0,"fertilizerCount":0}`,
	test: [['help'], ['view', 'farm'], ['view', 'inventory'], ['view', 'coins'], ['plant', 'wheat', 'spot', '1'], ['water'], ['harvest', 'spot', '1'], ['daily'], ['buy']],
};
